### PR TITLE
change charset to UTF8, so it can support more language

### PR DESCRIPTION
**Pull request by aszx87410**

### CODE REVIEW

**Comment by aszx87410** [comment]
As we discuss in the mail, modify and add some functions to better support multi-charset. Limited by browser's ability, local file can only be encoded in UTF-8. Remote file from internet will send two request, the first detect encoding by content-type from response, the second specify the correct encoding.

**Comment by yashagarwal1411** [comment]
Hey, thanks for the changes. I will just go through the changes and merge the request. After this fix will most of the languages be automatically supported?

**Comment by aszx87410** [comment]
Yes, at least users can use their own subtitle file encoded in UTF8, which support lots of languages.

**Comment by yashagarwal1411** [comment]
Released the changes in latest version 3.3.21 of the extension :) Although there is some change in implementation. OpenSubtitles will never return the charset in Content-Type header for the download url. Instead they were sending this charset as a parameter in the first Api where I get other details like download url etc. Using this charset has made it feasible for me to support any language now :)

**Pull request merged**
